
services:
  backend:
    build: ./backend
    ports:
      - "5200:5200"
    networks:
      - intrusai-net

  frontend:
    build: ./frontend
    ports:
      - "5175:5175"
    networks:
      - intrusai-net

networks:
  intrusai-net:
    driver: bridge
