version: '3.9'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5200:5200"
    container_name: intrus_ai3-backend-1

  frontend:
    build:
      context: ./frontend
    ports:
      - "5175:5175"
    container_name: intrus_ai3-frontend-1
    depends_on:
      - backend
