version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5200:5200"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/intrusai
    networks:
      - intrus_net

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - intrus_net

  mongodb:
    image: mongo:6.0
    container_name: intrus_mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - intrus_net

volumes:
  mongo_data:

networks:
  intrus_net:

