version: '3'

services:
  backend:
    build: ./backend
    ports:
      - "5200:5200"
    working_dir: /app
    volumes:
      - ./backend:/app
    command: node server.js

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: npm run dev -- --host
