version: '3.8'

services:
  backend:
<<<<<<< HEAD
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5200:5200"
    environment:
      - NODE_ENV=production
    volumes:
      - ./backend:/app
    depends_on:
      - snort
=======
    build: ./backend
    ports:
      - "5200:5200"
>>>>>>> 2c1228656c6892a7dc2a97afeb9b01eecafd7370
    networks:
      - intrusai-net

  frontend:
<<<<<<< HEAD
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    networks:
      - intrusai-net

  snort:
    image: snort3/snort3
    container_name: snort
    networks:
      - intrusai-net
    command: snort -i eth0 -A console

=======
    build: ./frontend
    ports:
      - "5175:5175"
    networks:
      - intrusai-net

>>>>>>> 2c1228656c6892a7dc2a97afeb9b01eecafd7370
networks:
  intrusai-net:
    driver: bridge
