# backend/Dockerfile

FROM node:18-alpine

# Set working directory
WORKDIR /app

# Copy package files and install dependencies
COPY package*.json ./
RUN npm install

# Copy backend source code
COPY . .

# Expose the backend port
EXPOSE 5200

# Start the server
CMD ["node", "server.js"]
