# Use official Python image
FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Copy your backend code
COPY . /app

# Install dependencies
RUN pip install flask flask-socketio eventlet scapy

# Expose the port your Flask app runs on
EXPOSE 5200

# Start your Python server
CMD ["python", "sniffer_server.py"]
