# server/Dockerfile

FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

# Copy rest of the server code
COPY . .

# Expose API port
EXPOSE 4000

# Start server
CMD ["npm", "start"]
